test pipeline

diff --git a/.github/workflows/robot-tests.yml b/.github/workflows/robot-tests.yml
--- a/.github/workflows/robot-tests.yml
+++ b/.github/workflows/robot-tests.yml
@@ -1,30 +1,41 @@
-name: Robot Framework Tests
+name: Robot Framework CI
 
-on: [push]
+on:
+  push:
+    branches:
+      - master
+  pull_request:
+  workflow_dispatch:
 
 jobs:
-  run-tests:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v2
-
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'
-
-    - name: Install Dependencies
-      run: |
-        pip install -r requirements.txt
-
-    - name: Run Robot Framework Tests
-      run: |
-        robot --report NONE --outputdir results testcases/
-
-    - name: Upload Robot Framework Results
-      uses: actions/upload-artifact@v2
-      with:
-        name: robot-results
-        path: results/
+    Run-Test:
+      runs-on: ubuntu-20.04
+      steps:
+        - name: Checkout repository
+          uses: actions/checkout@v1
+        - uses: actions/cache@v2
+          id: cache
+          with:
+            path: ~/.cache/pip
+            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
+        - name: Install pip dependencies
+          run: |
+            pip install --upgrade pip
+            pip install -r requirement.txt
+        - name: Run Test
+          run: python -m robot --outputdir results testcases/
+        - name: Run Test and create report
+          run: python -m robot -d reports -x junit-report.xml testcases/
+        - name: Run Robot Framework tests and generate report
+          run: |
+             echo "ROBOT_RC=$?" >> "$GITHUB_ENV"  
+        # - name: If Auto Test Pass Rate Not 100%, Job Will Fail
+        #   if: env.ROBOT_RC != '0'
+        #   run: |
+        #     echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
+        #     exit 1
+        - name: Publish test results
+          uses: actions/upload-artifact@v2
+          with:
+            name: robot-test-results
+            path: results
